# Generated by Django 2.1.7 on 2019-02-26 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['Date', 'Time', 'Title']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='Organizer',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='poster',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Poster',
            field=models.ImageField(default=1, upload_to='event_posters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
