# Generated by Django 2.1.7 on 2019-02-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190226_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Time',
            field=models.TimeField(),
        ),
    ]
